### ISSUE TITLE
Some Problem in decompose = "3.0.0" and decompose-router = "0.7.0", kotlin = 2.0.0-RC3 

### ISSUE THREAD

**Issue by Crazy-Kyle** [xxfast/Decompose-Router#96]
java.lang.NoSuchMethodError: No static method defaultComponentContext(Landroidx/savedstate/SavedStateRegistryOwner;)Lcom/arkivanov/decompose/DefaultComponentContext; in class Lcom/arkivanov/decompose/DefaultComponentContextBuilderKt; or its super classes (declaration of 'com.arkivanov.decompose.DefaultComponentContextBuilderKt' appears in /data/app/~~L1S-oIHxUhEcjgRGgdto5g==/space.aigod.platformapp-SIRXTKhgAoHwjyx7HCX9QA==/base.apk!classes7.dex)
                                                                                                    	at io.github.xxfast.decompose.router.DefaultRouterContextKt.defaultRouterContext(DefaultRouterContext.kt:9)
                                                                                                    	at space.aigod.platformapp.MainActivity.onCreate(MainActivity.kt:29)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8577)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8541)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3884)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4049)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8348)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by Crazy-Kyle** [comment]
kotlin = 2.0.0-RC3
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

**Comment by xxfast** [comment]
Hi! Working on adding kotlin 2.0 support soon 🤞

**Comment by xxfast** [comment]
Hi @Crazy-Kyle Decompose 3.0.0 and Kotlin 2.0.0 should now be supported on [Decompose Router@0.8.0](https://github.com/xxfast/Decompose-Router/releases/tag/0.8.0)
